### PR TITLE
Revising "Cloning a Repository from Github to Github Desktop"

### PR DESCRIPTION
**Pull request by lily-soetebier**
# Revising "Cloning a Repository from Github to Github Desktop"
This pull request is referenceing the changes I have made to the *Cloning a Repository from Github to Github Desktop* file. My changes were made to make this set of instructions easier for a new user to prepare for and interact with.

### Presented info from users' point of view
* Added in the Introduction section to explain what cloning is and why a user may want to do it.
    >#### Introduction
    > Cloning a repository allows you to save a copy of a repository hosted on GitHub to your computer. However, this copy is still connected to the original remote repository. Using GitHub Desktop and your text editor of choice, you will manage and edit the files in this repository on your local computer, and then post your updates for review.
### Focus on users' goals
* Created a Prerequisites subsection to ensure that the readers are oriented to the task.
  >#### Prerequisites
  > Before you can clone a repository you must:
  >1. Have created and authenticated a GitHub account and have your credentials handy.
  >2. Sign in to **both** {% data variables.location.product_location %} and {% data variables.product.prodname_desktop %} before you start to clone. 
  >3. Install GitHub Desktop on to your computer. For more information on installing GitHub Desktop, see "[AUTOTITLE](/desktop/installing-and-authenticating-to-github-desktop/installing-github-desktop)."
  >4. Check that you have permission to clone the repository. If you do not, contact the original creator or another admin of the repository to gain access.

### Provides clear, step-by-step instruction
I moved step 1 of the original instructions to the prerequisite section as step 2.
>  2. Sign in to **both** {% data variables.location.product_location %} and {% data variables.product.prodname_desktop %} before you start to clone.

## Coaching

Describe what content, if any, you revised and why via the TO criteria: 

### Writing for intended audience
* Edited the wording in step 2 to better fit a novice audience by employing the common metaphors used for navigating and storing files. The phrases "folders" and "libraries" are more accessible to novices than "local directory". Additionally, this prepares the reader for a pop-up to open.
    
    **Before:**
    > Click **Choose...** navigate to a local directory where you want to clone the repository.

    **After**
    > Click **Choose...**. Use the pop-up that opens to select which folder you want to house the cloned repository in. 

### Provides clear, step-by-step instruction
* Added the Heading "Cloning the Repository" to differentiate the steps from the added "Prerequisites" section.
* Added the word "both" to the second pre-requisite step to provide extra emphasis on how important it is to be logged in on desktop and the web.
  
  **Before:**
  >Sign in to {% data variables.location.product_location %} and {% data variables.product.prodname_desktop %} before you start to clone.

  **After:**
  > Sign in to **both** {% data variables.location.product_location %} and {% data variables.product.prodname_desktop %} before you start to clone.

* Created three new steps to effectively guide the user from opening GitHub on their browser to the included second step of selecting where to save the cloned repository.
  > 1. Open GitHub in your browser, and navigate to the repository you want to clone.
  > 2. Click the dropdown arrow on the green "Code" button on the top right side of the repository's main page. 
    > Screen shot of the top bar of the repository's main page, highlighting in white the right most button labeled "Code"  
  > 3. Select "Open with GitHub Desktop". _GitHub Desktop should automatically open when you click this option._
  > Screenshot of the "Code" pop-up window.
  > 
  >>**Note: You may recieve a pop-up, like the one below taken from Google Chrome, asking for permission. 
  Screenshot of Google Chrome's pop-up for opening GitHub Desktop
  > It is reccomended to select "always allow". 
  > 
  >>If GitHub Desktop does not open, and you do not recieve a notification, check your browser's pop-up settings.

* Revised the wording of step 4 to provide more context.

  **Before:**
  > Click Choose... and navigate to a local directory where you want to clone the repository.

  **After:**
  > Once GitHub Desktop is open, click **Choose...** on the open pop-up. Use the resulting pop-up to select which folder you want to house the cloned repository in. 

* Added in step 5 as a way to help the novice user self-check that they are cloning the repository in the correct location before they finalize the cloning.
  > Check that the address in the "Local Path" bar matches the location you just selected. 
  creenshot of the "URL" tab of the "Clone a Repository" window. In the "Local Path" field, the location you selected should be listed.
  >> **Note:** The last portion of the address should *always* be the repository's name.

### Writing for intended audience
* Included an italicised prompt in step 3 to ensure that the user is aware that GitHub Desktop should automatically open. This is something a novice might assume, but the specificity may be useful if they have any issues (as detailed in the note within this step).
  > _GitHub Desktop should automatically open when you click this option._

### Focus on users' goals
* Moved the tip on using desktop to clone to the end of the instructions to keep the user focused on the task at hand, rather than an alternate approach.

  > **Tip:**  You also can use {% data variables.product.prodname_desktop %} to clone repositories that exist on {% data variables.product.prodname_dotcom %}.  For more information, see "[AUTOTITLE](/desktop/adding-and-cloning-repositories/cloning-and-forking-repositories-from-github-desktop)."

### Provides clear, step-by-step instruction
* All alerting moves (Tips, Notes, etc.) were formatted or reformatted as block quotes to ensure that they stood out from the rest of the instructions

### CODE REVIEW

**Comment by caimile** [comment]
Comments about **Staging**
I like the idea of having the prerequisites there so that users know what they need to have access to before attempting to clone a repository. Do you think that some of that information about creating/authenticating the GitHub account is duplicative or iterative of what's in Part 1 of the doc, though? Maybe we could add a section in this part that houses a couple of conceptual statements about what it means to clone a repository--specifically why a user would want or need to do this as part of their workflow (i.e. it brings a copy of the repository to your local device so that you can work on it and contribute to a project by pushing the changes you made in the clone or something like that) (sorry for my ambiguity).

Comments about **Coaching**
These changes look good to me! Helps clarify a bunch of the steps. Maybe find a way to remove the ellipses? They might be distracting/unnecessary to a reader. (Maybe you already did and I can't tell- sorry, still getting used to how everything looks!)

Comments about **Alerting**
The block quotes are a good idea- helps it stand out against everything else. There was another piece of info that I saw in the **Staging** section that could potentially be turned into an "alert" as well: "_**Note: You may recieve a pop-up, like the one below taken from Google Chrome, asking for permission._"

**Comment by lily-soetebier** [comment]
@caimile I agree with your suggestion to add in a blurb on what cloning is and why they would want to do that. I feel like that would be helpful.  I think given the scenario we are revising for--a novice user who is looking to interact with existing documentation for the first time--I think including a note about needing your own GitHub account might be necessary. I'm not totally married to keeping it in there; I just think it could be useful if the user is going straight into work trying to access existing docs. @MBethmorris thoughts?

**Comment by lily-soetebier** [comment]
I went ahead and added in that intro section and updated the initial pull request comment with that information.

**Comment by MBethmorris** [comment]
@lily-soetebier your updates are really geared toward the novice user. The move of the step 1 to the prereq section was a good edit. The addition of the Cloning the Repository heading helps clarify and move your eye along the text to the next section. I think the line breaks and headers are an important piece to helping the reader see the content on the page as steps. 

As far as the info on needing your own GitHub content- it can be helpful as long as you feel it is not too much info for this piece. As a new user- I find it useful.

**Review by MBethmorris — COMMENTED** [review]
@lily-soetebier updates look good. Most of my review comments are already posted but wasn't sure if I had to post here as well.

**Pull request merged**
